[package]
name = "dinning_philosophers"
version = "0.1.0"
authors = ["Luis Tinajero Muñozcano <ltm150895@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
